export const COUNTRY_CODES = [
  { code: "+1", country: "USA", label: "USA (+1)" },
  { code: "+1", country: "Canada", label: "Canada (+1)" },
  { code: "+44", country: "UK", label: "UK (+44)" },
  { code: "+91", country: "India", label: "India (+91)" },
  { code: "+61", country: "Australia", label: "Australia (+61)" },
  { code: "+49", country: "Germany", label: "Germany (+49)" },
  { code: "+33", country: "France", label: "France (+33)" },
  { code: "+81", country: "Japan", label: "Japan (+81)" },
  { code: "+86", country: "China", label: "China (+86)" },
  { code: "+55", country: "Brazil", label: "Brazil (+55)" },
  { code: "+27", country: "South Africa", label: "+27 (South Africa)" },
  { code: "+971", country: "UAE", label: "+971 (UAE)" },
  { code: "+65", country: "Singapore", label: "+65 (Singapore)" },
  { code: "+7", country: "Russia", label: "+7 (Russia)" },
  { code: "+39", country: "Italy", label: "+39 (Italy)" },
  { code: "+34", country: "Spain", label: "+34 (Spain)" },
  { code: "+52", country: "Mexico", label: "+52 (Mexico)" },
  { code: "+62", country: "Indonesia", label: "+62 (Indonesia)" },
  { code: "+92", country: "Pakistan", label: "+92 (Pakistan)" },
  { code: "+880", country: "Bangladesh", label: "+880 (Bangladesh)" },
  { code: "+84", country: "Vietnam", label: "+84 (Vietnam)" },
  { code: "+63", country: "Philippines", label: "+63 (Philippines)" },
  { code: "+20", country: "Egypt", label: "+20 (Egypt)" },
  { code: "+234", country: "Nigeria", label: "+234 (Nigeria)" },
  { code: "+90", country: "Turkey", label: "+90 (Turkey)" },
  { code: "+98", country: "Iran", label: "+98 (Iran)" },
  { code: "+66", country: "Thailand", label: "+66 (Thailand)" },
  { code: "+353", country: "Ireland", label: "+353 (Ireland)" },
  { code: "+41", country: "Switzerland", label: "+41 (Switzerland)" },
  { code: "+46", country: "Sweden", label: "+46 (Sweden)" },
  { code: "+47", country: "Norway", label: "+47 (Norway)" },
  { code: "+45", country: "Denmark", label: "+45 (Denmark)" },
  { code: "+31", country: "Netherlands", label: "+31 (Netherlands)" },
  { code: "+32", country: "Belgium", label: "+32 (Belgium)" },
  { code: "+43", country: "Austria", label: "+43 (Austria)" },
  { code: "+351", country: "Portugal", label: "+351 (Portugal)" },
  { code: "+30", country: "Greece", label: "+3 Greek" },
  { code: "+420", country: "Czechia", label: "+420 (Czechia)" },
  { code: "+48", country: "Poland", label: "+48 (Poland)" },
  { code: "+36", country: "Hungary", label: "+36 (Hungary)" },
  { code: "+40", country: "Romania", label: "+40 (Romania)" },
  { code: "+972", country: "Israel", label: "+972 (Israel)" },
  { code: "+966", country: "Saudi Arabia", label: "+966 (Saudi Arabia)" },
  { code: "+965", country: "Kuwait", label: "+965 (Kuwait)" },
  { code: "+974", country: "Qatar", label: "+974 (Qatar)" },
  { code: "+64", country: "New Zealand", label: "+64 (New Zealand)" },
  { code: "+60", country: "Malaysia", label: "+60 (Malaysia)" },
];
